// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class VacancysearchTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void vacancysearch() {
    driver.get("https://spb.superjob.ru/");
    driver.findElement(By.cssSelector(".\\_16Ula")).click();
    driver.findElement(By.xpath("//input[@name=\'keywords\']")).sendKeys("Developer");
    driver.findElement(By.cssSelector(".oRqVe > .\\_9gypz")).click();
  }
}
